### ISSUE TITLE
Docker Quickstart Terminal does not respect installed terminal (Mac OS X)

### ISSUE THREAD

**Issue by rhfung** [docker/toolbox#101]
The Docker Quickstart Terminal opens up the default Terminal app on Mac. Since I have installed iTerm, I expect it to open in iTerm. Kitematic > Exec, in contrast, knows to open the shell in iTerm.

**Comment by mchiang0610** [comment]
@rhfung Thanks for reporting this. The quick start terminal is really meant as a demo to get people started. You can use iTerm as well! 

Hope this helps. Thanks!

**Comment by rmartin** [comment]
hey @rhfung , 

I was a confused by this as well as it seemed that the quickstart terminal was the recommended way to start running docker. A little more digging and I came across the install instructions on OS X, which walk you through the steps necessary to setup the docker command within your own shell. You can follow this page from start to finish to avoid using the quickstart all together, or if you've already run the quickstart to get the 'default' vm up and running then you can skip to the 'from your shell' section. 

Specifically, you need to grab the commands from the docker-machine env default output and then put those in your shell start up script (.bash_profile or .zshrc) so that you can run the docker commands from there. 

Hope this helps others that might run into the same thing in the future. 

https://docs.docker.com/installation/mac/
https://docs.docker.com/installation/mac/#from-your-shell

Cheers,
Roy

**Comment by JikkuJose** [comment]
A question about running from different shell (`zsh` in my case):

Why is it the command: `eval "$(docker-machine env default)"` not run automatically? I would have assumed it will automatically get run when I run: `docker-machine start default`.
