### ISSUE TITLE
Toolbox hangs during setting of environment variables (Windows 8.1)

### ISSUE THREAD

**Issue by jischebeck** [docker/toolbox#116]
When running the "Docker Quikstart Terminal", the startup stops after setting environment variables.
The virtualbox is up and running. 

```
Welcome to Git (version 1.9.5-preview20150319)
Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
Machine default already exists in VirtualBox.
Starting machine default...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Setting environment variables for machine default...
```

**Comment by gvlx** [comment]
It seems `docker-machine.exe` running in windows always wants the `--shell` option set.

As the `start.sh` script is a bash script (bash is installed as part of the MSYS git package) this cases problems.

Changing line 35 from
`eval "$($DOCKER_MACHINE env $VM)"`
to
`eval "$($DOCKER_MACHINE env $VM --shell $SHELL)"`
solves the problem (will it still work on other systems?)


Maybe docker-machine should check the `SHELL` environment variable before throwing the towel?

**Comment by tiangolo** [comment]
I copy my comment from here: https://github.com/docker/toolbox/issues/66#issuecomment-138755855 in this post, as I think it's probably the same issue.

-----

I think @ameyrk nailed it down for Windows in this comment https://github.com/docker/toolbox/issues/66#issuecomment-131580971. 

I confirm the same issue happens in Windows 7:

After a sleep / wake cycle, Windows detects the Host-Only network as a "duplicate" and changes its IP. After that, docker-machine (or the Quickstart terminal) doesn't work anymore.

It is probably caused by this VirtualBox bug (from 4 years ago): https://www.virtualbox.org/ticket/9151, so there doesn't seem to be a fix soon from VirtualBox. And it's probably a Windows bug.

-----------

**The quick workaround that worked for me was:**

* Open VirtualBox
* Go to File -> Preferences -> Network -> Host-only Networks
* Docker Toolbox probably created a second Host-only network, probably named "VirtualBox Host-Only Ethernet Adapter # 2", double click that
* Change the "IPv4 Address" from something like 192.168.99.1 to something like 192.168.99.2 (you will probably have to increase / decrease the IP every time). But it's important that the IP actually changes.
* Hit OK. If the IP changed (it should have changed), you will be prompted for you "Windows Administrator OK" (or however it's named).

After that, the docker-machine and the Quickstart Terminal should work, and that way, you don't have to restart your whole Windows.

**Comment by hmny** [comment]
solved my problem on Windows 10

**Comment by itibook** [comment]
just to confirm that @tiangolo's solution worked for me...

**Comment by mchiang0610** [comment]
Seems to be fixed.

**Comment by sebastien-helbert** [comment]
@tiangolo +1

**Comment by yanqiw** [comment]
@tiangolo +1
For Win 7,  I need to delete all the adapters, and start the VM again. The issue is fixed.
