### ISSUE TITLE
[osx] start.sh doesn't work with two user shells

### ISSUE THREAD

**Issue by tjwudi** [docker/toolbox#210]
In `start.sh`, I see few lines getting user shell like this.

```
USER_SHELL=$(dscl /Search -read /Users/$USER UserShell | awk '{print $2}')
if [ "$USER_SHELL" = "/bin/bash" ] || [ "$USER_SHELL" = "/bin/zsh" ] || [ "$USER_SHELL" = "/bin/sh" ]; then
  $USER_SHELL --login
else
  $USER_SHELL
fi
```

But I actually have two user shells.

```bash
$ echo $(dscl /Search -read /Users/$USER UserShell | awk '{print $2}')
/bin/zsh /bin/bash
```

This can lead to the error when launching toolbox.

```
docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com

/bin/bash:1: command not found: ^H
/bin/bash:1: command not found: N^H
/bin/bash:1: command not found: ^H
/bin/bash:1: command not found: ^H
/bin/bash:4: unmatched "
/bin/bash:1: bad pattern: ^@^@^@^@^@^Y^@^@^@H^@^@^@__PAGEZERO^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^Y^@^@^@(^B^@^@__TEXT^@^@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@^H^@^@^@^@^@^G^@^@^@^E^@^@^@^F^@^@^@^@^@^@^@__text^@^@^@^@^@^@^@^@^@^@__TEXT^@^@^@^@^@^@^@^@^@^@�^K^@^@^A^@^@^@_^\^G^@^@^@^@^@�^K^@^@^B^@^@^@^@^@^@^@^@^@^@^@^@^D^@\M-^@^@^@^@^@^@^@^@^@^@^@^@^@__stubs^@^@^@^@^@^@^@^@^@__TEXT^@^@^@^@^@^@^@^@^@^@L(^G^@^A^@^@^@b^D^@^@^@^@^@^@L(^G^@^A^@^@^@^@^@^@^@^@^@^@^@^H^D^@\M-^@^@^@^@^@^F^@^@^@^@^@^@^@__stub_helper^@^@^@__TEXT^@^@^@^@^@^@^@^@^@^@�,^G^@^A^@^@^@^^G^@^@^@^@^@^@�,^G^@^B^@^@^@^@^@^@^@^@^@^@^@^@^D^@\M-^@^@^@^@^@^@^@^@^@^@^@^@^@__cstring^@^@^@^@^@^@^@__TEXT^@^@^@^@^@^@^@^@^@^@^N4^G^@^A^@^@^@a�^@^@^@^@^@^@^N4^G^@^@^@^@^@^@^@^@^@^@^@^@^@^B^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@__const^@^@^@^@^@^@^@^@^@__╭
```

**Comment by mchiang0610** [comment]
@tjwudi Thanks for this, and the pull request.

**Comment by OscarF** [comment]
How/when are releases done? Would really appreciate a new release (with installer) for this fix.

**Comment by DarthFudd** [comment]
For me it was sufficient to select the last line by replacing `awk '{print $2}'` with `awk 'END{print $2}'` , but I can't think of a good justification for using "it's the last line" as the selection criteria. Why not the first line, or the line among several which appears the most often? If someone has two different shells, there's no reliable way for the install process to pick the one that the user desires.

Maybe this would be better: eliminate duplicates, and if duplicates still exist, pick one but warn the user. Tell them that we picked one shell among many, and that if they didn't like the selection, they can change it after the install is finished. Don't prompt people who have only one selection, on the theory that anyone who truly wants to use a shell that isn't listed by `dscl` won't need a prompt to remind them to set it up after the install.

Finally, while I've never heard of anyone having a shell path with a space in it, using `$2` makes implicit assumptions about what characters are involved. I'm not sure if that possibility is worth addressing, but in awk one method is to blank out $1 and print the rest. I won't lobby for that change, since a space in the shell path would presumably break *lots* of things, but I'll mention the option just in case. Maybe someone truly does have a shell name which includes spaces, carriage returns, curly brackets...
