### ISSUE TITLE
Windows Quickstart Terminal is SSHed in (different UX)

### ISSUE THREAD

**Issue by nathanleclaire** [docker/toolbox#220]
Based on https://github.com/docker/machine/issues/1930#issuecomment-145990335, it seems some users are seeing the Windows terminal as SSHed into the VM, but they expect to be in a "native" Windows shell with `docker-machine` available, etc.

If it's the expected behavior that's fine, but we should document it to avoid confusion.  Although, I think I'd argue for a consistent experience across all platforms.

cc @moxiegirl @mchiang0610 @jeffdm Any ideas what's going on here?

**Comment by jeffdm** [comment]
We switched to this temporarily until we could get the `docker` binary to work with Git 2.5 for Windows. See #136

**Comment by jeffdm** [comment]
The winpty suggestion seems like a great fix though, working on testing it out!

**Comment by ramgovind** [comment]
Docker Toolbox 1.8.2c has introduced these bugs:
1. None of the folders on the C drive are visible except C:/Users.  
2. Cannot run shell script files e.g. build.sh

So I had to revert to 1.8.2a to continue my work. However, 1.8.2a cannot tty to terminal which is fixed in 1.8.2c.

Please fix the above bugs.

**Comment by jeffdm** [comment]
@ramgovind thanks for letting us know - working on it!

**Comment by jeffdm** [comment]
This should be fixed by #221, and in release v1.8.2d
