### ISSUE TITLE
specify docker_opts

### ISSUE THREAD

**Issue by NoumanSaleem** [docker/toolbox#258]
Is there a way to specify docker_opts when using docker-toolbox on OSX?

thanks.

**Comment by bhanuvrat** [comment]
+1

**Comment by SvenDowideit** [comment]
@nathanleclaire are the docs for how to customize the b2d profile from Docker machine?

otherwise - see the last example in https://github.com/boot2docker/boot2docker/blob/master/doc/FAQ.md#local-customisation-with-persistent-partition

you can set the `EXTRA_ARGS` inside the VM, and those will be used.

**Comment by nathanleclaire** [comment]
> @nathanleclaire are the docs for how to customize the b2d profile from Docker machine?

By using `--engine-opt` etc. flags: https://docs.docker.com/machine/reference/create/#specifying-configuration-options-for-the-created-docker-engine:b2f7ec83b933df3ed63b2a387c4e9c83
