### ISSUE TITLE
shell_exec + "Cannot connect to the Docker daemon. Is the docker daemon running on this host?"

### ISSUE THREAD

**Issue by wujozdep** [docker/toolbox#380]
Hello,

I can't run docker via shell_exec php.
Docker runs in terminal command line, but not working via php shell_exec

shell_exec('whoami') shows "admin"
User "admin" is added to the docker group (docker runs in command line of user 'admin')
There's problem only in running docker in php script.

Can anyone help?

**Comment by ChrisBAshton** [comment]
+1, I have the same question.

Inside the _shell_ (as ec2-user), I can run `php -r "echo shell_exec('docker run my-docker-image');"` and Docker runs as expected.

Inside the _browser_, if I access an endpoint with `echo shell_exec('docker run my-docker-image');`, I get the following error: `Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

I think I need to start my daemon with a certain flag configured (e.g. `--ip`), and run my container with a certain flag configured, but I'm not sure what flag that is! Any help would be really appreciated, because I can't find any tutorials or guides on how to execute Docker from PHP.

**Comment by jeffdm** [comment]
It seems that your shell environment isn't set up in the `shell_exec` instance. Make sure to set:

`DOCKER_HOST`
`DOCKER_CERT_PATH`
`DOCKER_TLS_VERIFY`

Thanks for the issue -
