### ISSUE TITLE
 Docker Quickstart Terminal window doesn't set up a terminal window

### ISSUE THREAD

**Issue by Karla-Isabel-Sandoval** [docker/toolbox#390]
Section 2 of Step 3 on 'https://docs.docker.com/mac/step_one/', How to Install Docker, is not setting up a Quickstart Terminal Window. I relaunched  Docker Quick Start from Launcher several times, but it is not launching.

**Comment by nathanleclaire** [comment]
What's the output of `docker-machine ls` in another terminal?  What's the output of `docker-machine --debug start`?

**Comment by kscott5** [comment]
I had similar issues after uninstalling Docker Toolbox version 1.9.1i and installing version 1.10.0.

![dockertoolbox1 10-capture](https://cloud.githubusercontent.com/assets/132991/12903443/4bb9daf0-ce8d-11e5-8936-81cf033c3f48.PNG)

The uninstall didn't remove the Oracle ViturlBox Virtual Ethernet adapters etc. So I fixed this issue by uninstall Docker Toolbox and Oracle VirtualBox from the Windows Programs and Features.

Then installing the Docker Toolbox version 1.10 and executing the Docker Terminal ran successfully with problems. (Note it took awhile for the terminal to finish configuring the default VM but I ran docker run hello-word just fine)

The reason I installing Docker Toolbox version 1.10 was to fix docker login issues on Windows which logged in successfully too.

**Comment by jeffdm** [comment]
@Karla-Isabel-Sandoval Thanks for the issue! Are you still seeing this?

@kscott5 thanks!

**Comment by kscott5** [comment]
It's working for me since I uninstalled/reinstalled the latest version


-------- Original message --------
From: Jeffrey Morgan
Date:02/17/2016 7:05 PM (GMT-06:00)
To: docker/toolbox
Cc: Karega Scott
Subject: Re: [toolbox] Docker Quickstart Terminal window doesn't set up a terminal window (#390)


@Karla-Isabel-Sandoval<https://github.com/Karla-Isabel-Sandoval> Thanks for the issue! Are you still seeing this?

@kscott5<https://github.com/kscott5> thanks!

**Comment by nathanleclaire** [comment]
Cool, going to close this, @Karla-Isabel-Sandoval please re-open if you still have issues
