### ISSUE TITLE
Windows installation isn't functioning properly

### ISSUE THREAD

**Issue by moxiegirl** [docker/toolbox#43]
Are we going to fix this before shipping? This happened with the earlier version as well.  This is a fresh VM on Fusion.  I also saw the same thing on my hardware version.

![image](https://cloud.githubusercontent.com/assets/1347209/8918442/e522ea58-346c-11e5-9488-fa0cdf6d57c3.png)

**Comment by jeffdm** [comment]
Sorry for the delay, @moxiegirl

On `master`, the quickstart terminal on windows will now show "Something went wrong... please press any key to continue.." if an error occurs, instead of just closing.

As for the msysgit message, after some looking I don't believe there's a flag we can pass the msysgit installer to not show the error message. I'll keep looking but I'm not sure what we can do here.

Going to close this for now. You can find some manual test coverage here: https://github.com/docker/toolbox/blob/master/TESTING.md
