### ISSUE TITLE
Docker Toolbox Installer doesn't work

### ISSUE THREAD

**Issue by pytong** [docker/toolbox#498]
I have been trying to install docker toolbox on mac. It keeps saying it is Verifying but nothing happens.
I am running El Captian Version 10.11.4

<img width="509" alt="screen shot 2016-05-18 at 11 39 55 pm" src="https://cloud.githubusercontent.com/assets/2434654/15381899/dd458b0a-1d51-11e6-8d8d-ffd5254041e7.png">

**Comment by jasperlouie** [comment]
Also facing a similar problems on Windows, not sure if I should open a separate issue for it, or perhaps the cause is the same? Upon double clicking the icon for the latest installer, the toolbox icon appears on the bottom of the screen, and it appears as though a window is being made, but upon clicking the icon or mousing over and clicking the "window" above it, nothing happens, and it stays like this indefinitely.

![image](https://cloud.githubusercontent.com/assets/5083601/15423218/52cf7694-1e31-11e6-840d-41e004b6fe15.png)

![image](https://cloud.githubusercontent.com/assets/5083601/15423245/68ff8e54-1e31-11e6-8bce-dd3b420a7b5b.png)

**Comment by jasperlouie** [comment]
Disabled my antivirus when trying to install and that allowed me to complete the installation process.
