### ISSUE TITLE
Hash of release file not match

### ISSUE THREAD

**Issue by macdao** [docker/toolbox#644]
I downloaded DockerToolbox-17.04.0-ce.exe from https://github.com/docker/toolbox/releases

and I got md5 and sha256 is
MD5 (DockerToolbox-17.04.0-ce.exe) = b43a685081eca22a72c056d8d2666615
9157ed0db9cac984fbd5f308b7cf92f27c449185efa42e64eaaf3c7a747f5144  DockerToolbox-17.04.0-ce.exe

while the txt from the url is:
f6eb7b5b1e244333337ad24231dfd56d  DockerToolbox.exe
987021e1f752515a6868b51e01cf4a1e245d7bb1c26c17dfdf5a81f2a41d720c  DockerToolbox.exe

none of them matches

**Comment by hmtelbi** [comment]
I checked the latest releases (17.05.0-ce) and noticed that the published and the actual hash sums still do not match.

Calculcated sha256 sum:
f81f859f68989007f1da0204f170a9c98fd7b65a7c2db40398739d7c8dec29e8

Published sha256 sum:
ba292bdc2d2177106d359767b800856029031768b6c68413df859234a17ec535

Has the executable been compromised?

**Comment by koumdros** [comment]
This is still happening, noticed it on all recent releases, just checked again for 17.10 & 17.12, nothing matches, neither the MD5 or the SHA256 hashes.

Thought of a possible MitM attack, downloaded in 3 and 4 respectively different locations, nope the issue is real.

This is... strange at least?  it is at least ...strange to actually post hashes that dont match,.

**Comment by RudiBob** [comment]
looking at https://github.com/docker/toolbox/issues/651

"hmtelbi commented on Jun 2
I noticed that the windows executable is digitally signed.
It seems that the published checksums are calculated before the signing process takes place.
Since the signing process modifies the executable, the actual checksums will be different from the published checksums."

**Comment by limist** [comment]
Confirmed with 17.12.0-ce, the hashes don't match.  They need to be updated, or simply omit the hash *.txt files entirely, thanks.

**Comment by koumdros** [comment]
This is a pain in the ass, as it breaks automation tools when they check whether a file matches the publishes checksum , and creates unnecessary friction in many ways,

**Comment by shin-** [comment]
Fixed for https://github.com/docker/toolbox/releases/tag/v18.01.0-ce
