### ISSUE TITLE
Win7 pro: docker toolbox installation does not install service

### ISSUE THREAD

**Issue by Vysarat** [docker/toolbox#760]
I ran the docker toolbox installer with all default settings. The installer did not give me any errors, it claims the installation was successful, yet the windows service was not installed.

Most docker commands give me this error:
```error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.```

when I check my list of services, I don't see one called "Docker for windows" (or anything with the word Docker in it).

Docker version: 18.03.0-ce, build 0520e24302

**Comment by thaJeztah** [comment]
Windows 7 does not have native support for running Windows containers, so to run Docker on Windows 7, Docker Toolbox installs a VirtualBox VM, in which docker is installed. Because of that, you won't see the docker daemon running on your host.

The Docker CLI (by default) looks for a named pipe to connect to the docker API; when running Docker Toolbox, you have to set an environment variable to tell the CLI to connect to a "remote" daemon, instead of a local one (the VM is seen as a remote host);


Try running the `docker-machine env` command, which will show instructions to set up the environment variables for the current shell:
```
docker-machine env
```

**Comment by Vysarat** [comment]
That makes sense. I was getting this error when running `docker-machine env`:
```Error checking TLS connection: Host is not running```
I assumed it was because the service wasn't running, but after some further digging it looks like it was happening because I was using a VPN.

**Comment by HixOba** [comment]
Hi @Vysarat, glad to hear you have docker toolbox running ok on your windows 7 pro. Would you mind outlining what steps you took to get this working please? I am trying to get this working on my windows 7 pro local system with success. Thanks

**Comment by barbrady123** [comment]
@HixOba in case you are still having issues (or anybody else is)....running 

`docker-machine env`

Gives you the command to run, which solved my issue...specifically:

`@FOR /f "tokens=*" %i IN ('docker-machine env') do @%i`
