### ISSUE TITLE
Don't track with mixpanel

### ISSUE THREAD

**Issue by arubdesu** [docker/toolbox#87]
At the very least add a disclaimer that you have [tracking in the postinstall](https://github.com/docker/toolbox/blob/master/osx/mpkg/boot2dockeriso.pkg/Scripts/postinstall#L63)
For Mac sysadmins the entire postinstall violates most if not all of the [commandments of packaging](https://www.afp548.com/2010/06/03/the-commandments-of-packaging-in-os-x/). Insert 'your package is bad and you should feel bad' meme.
Because I want you to succeed and make my docker experience better.

**Comment by arubdesu** [comment]
Wait, you're doing it in [the dist](https://github.com/docker/toolbox/blob/master/osx/mpkg/Distribution#L95), too? smh

**Comment by rbq** [comment]
I came here because I noticed the installer secretly sending data to a user tracking service. I immediately uninstalled the Docker binaries until I can figure out what's going on. Is Docker, Inc. actually introducing usage tracking to their software products? This kind of anti-feature being hidden in development software makes me wonder about production. Is there or will there be spyware in the binaries, telling Docker, Inc. when/where/what kind of machines I provision, what kind of workload me or my clients run, etc.?

**Comment by arubdesu** [comment]
We can back away from conspiracy theories, putting it in the dist (in plaintext) means it says 'hello' from an IP once when it starts, putting it in the postinstall means they can tell who succeeded with the install, since it could bail at any point previous to that.
It's a poor choice to not provide an opt-out or disclaimer before shipping, I agree, any phoning home should be clearly stated. But as they say, don't attribute to malice: my friend @bruienne is [on the case](https://github.com/macadmins/toolbox/commit/7b715c55de9d1847cebe190b69641299bfcd95b4) helping enlighten them. And I can point to the exact links, whereas actually sleazy companies like Adobe obscure their proprietary BS.

**Comment by bruienne** [comment]
Hi @rbq - I and others (like @arubdesu) noticed the same thing and I'm working on a PR among other things to improve the overall installation experience for OS X users. As far as I understand from speaking with the devs and looking at the points in the installation process where the tracking is used, it's solely meant to track numbers of successful vs. unsuccessful installs, nothing else. There's no further malicious intent and I'm engaged with the devs to enable users to actively agree to sending the installation results vs. silently. That said, it's up to users in general to voice their opinion on whether this kind of tracking should be going on at all in order for them to feel comfortable installing and using the software.

**Comment by mchiang0610** [comment]
@arubdesu @rbq @bruienne Hi, just wanted to say sorry about this. We now require you to agree to being tracked in order to be tracked. 

Please note, you will be tracked if you agree to it, and the data that we send back is completely anonymous. All we are doing is letting us know if a set up error occurred. 

Again, sorry about this. We now require you to agree before we track.  If not, you won't be tracked. 

Thank you

**Comment by rbq** [comment]
@mchiang0610 @arubdesu @bruienne Thanks a lot, to all of you.

**Comment by arubdesu** [comment]
Please be explicit. You say something about 'headless', and while I know it won't run if installed by [Apple Remote Desktop](http://s.sudre.free.fr/Software/documentation/Iceberg/English.lproj/documentation/Plugins%20Pane.html), you're not saying there was any QA performed for a command line install as root with no users logged in. Also, this is now harder to tell what's going on, since the mixpanel code is in objective-C as part of an [installer plugin](https://github.com/docker/toolbox/blob/master/osx/installerplugins/overviewplugin/overviewpluginPane.m#L28-L56). 

Just say that's what you did, you changed up everything of his this works without saying what was performed, and I have to go play detective again.
